### ISSUE TITLE
Allow non-updating custom bookmark title

### ISSUE THREAD

**Issue by rlbartle** [igorlogius/auto-updating-bookmark#4]
Many websites have annoyingly long and unimportant info in their titles which I wish to keep out of the names of my bookmarks.

When the bookmark name is customised, in my opinion if doesn't have the 'AUB:' prefix then the name shouldn't be modified when the bookmark is updated. 

A trivial example would be a webcomic which appends the chapter number as a suffix in the title. In the case of a collection of webcomic bookmarks, it is preferable to have them concise and entitled with the actual name only.

**Comment by igorlogius** [comment]
Hi, thanks for taking the time to write this request. 

I made some small adjustments and released version `1.6.9` where you 
can now prevent the bookmark title from changing simply by removing the `AUR:` prefix from the bookmark title.  

Please try it out and let me know what if this covers your request requirements.

**Comment by rlbartle** [comment]
Thanks, it is now great.
