### ISSUE TITLE
Support Android

### ISSUE THREAD

**Issue by lune-stone** [igorlogius/auto-updating-bookmark#5]
Using Firefox 121.0

Currently you can install the add-on, but it doesn't appear to be functioning correctly. Specifically:

* Using the "Add-ons > create a auto updating bookmark" button doesn't create a bookmark.
* Bookmarks created on the desktop and synced to the device are not updated while navigating.
* As far as I can tell, there is no method to change the default bookmark folder location (how does one "right click" on a phone?).

**Comment by igorlogius** [comment]
Hi, thanks for reporing this issue, seems like i forgot to uncheck the android compatibility check. 

But i'll also be looking into if it is doable to make the addon android compatible in the future.

**Comment by igorlogius** [comment]
Seems that firefox on android still doenst support the bookmarks API 
ref. https://bugzilla.mozilla.org/show_bug.cgi?id=1625231 
Until that is changed/fixed, by the browser developers i can not do anything. Sorry.

**Comment by igorlogius** [comment]
Closing for now, since here is nothing todo at the moment and likely the addon will work out of the box as soon as Firefox on Android implements the missing bookmark API.
